-- TABELAS: Edição e Matéria
CREATE TABLE IF NOT EXISTS edicao (
    nome_jornal VARCHAR(100),
    numero_edicao INT,
    data DATE,

    PRIMARY KEY (nome_jornal, numero_edicao),

    CONSTRAINT fk_edicao_jornal
        FOREIGN KEY (nome_jornal)
        REFERENCES jornal(nome_jornal)
);

CREATE TABLE IF NOT EXISTS materia (
    id_materia INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(200) NOT NULL,
    subtitulo VARCHAR(200),
    resumo TEXT,
    conteudo TEXT NOT NULL,
    data DATE NOT NULL,
    status INT NOT NULL CHECK (status BETWEEN 0 AND 2),
    nome_jornal VARCHAR(100),
    numero_edicao INT,
    id_setor INT,

    CONSTRAINT fk_materia_edicao
        FOREIGN KEY (nome_jornal, numero_edicao)
        REFERENCES edicao(nome_jornal, numero_edicao),

    CONSTRAINT fk_materia_setor
        FOREIGN KEY (id_setor)
        REFERENCES setor(id_setor)
);
-- TABELA: Alocacao_Jornalista_Materia
CREATE TABLE IF NOT EXISTS alocacao_jornalista_materia (
    cpf_jornalista VARCHAR(11),
    id_materia INT,

    PRIMARY KEY (cpf_jornalista, id_materia),

    CONSTRAINT fk_alocacao_jornalista
        FOREIGN KEY (cpf_jornalista)
        REFERENCES jornalista(cpf_jornalista),

    CONSTRAINT fk_alocacao_materia
        FOREIGN KEY (id_materia)
        REFERENCES materia(id_materia)
);