-- Tabelas edicao (entidade fraca), materia e edicao_materia (associativa N:N).
CREATE TABLE IF NOT EXISTS materia (
    id_materia INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(150) NOT NULL,
    subtitulo VARCHAR(250),
    resumo TEXT,
    conteudo TEXT NOT NULL,
    data DATE NOT NULL,
    status INT NOT NULL CHECK (status BETWEEN 0 AND 2),
    nome_jornal VARCHAR(100) REFERENCES jornal(nome),
    numero_edicao INT REFERENCES edicao(numero),
    id_setor INT REFERENCES setor(id),
    cpf_editor_chefe CHAR(11) REFERENCES editor_chefe(cpf)
);


CREATE TABLE IF NOT EXISTS materia_jornalista (
    materia_id INT NOT NULL
        REFERENCES materia(id_materia) ON DELETE CASCADE,
    jornalista_cpf CHAR(11) NOT NULL
        REFERENCES jornalista(cpf) ON DELETE CASCADE,
    papel VARCHAR(50) DEFAULT 'Autor Principal',
    PRIMARY KEY (materia_id, jornalista_cpf)
);

CREATE TABLE IF NOT EXISTS edicao_materia (
    edicao_id INT NOT NULL
        REFERENCES edicao(id) ON DELETE CASCADE,
    materia_id INT NOT NULL
        REFERENCES materia(id_materia) ON DELETE CASCADE,
    pagina_inicio INT CHECK (pagina_inicio > 0),
    pagina_fim INT CHECK (pagina_fim >= pagina_inicio),
    PRIMARY KEY (edicao_id, materia_id)
);


CREATE INDEX IF NOT EXISTS idx_materia_setor
    ON materia(id_setor);

CREATE INDEX IF NOT EXISTS idx_materia_status
    ON materia(status);

CREATE INDEX IF NOT EXISTS idx_materia_editor
    ON materia(cpf_editor_chefe);