-- ============================================================
-- SEED DE MATERIA 
-- 60 registros
--
-- STATUS:
-- 0 = EM_ANDAMENTO
-- 1 = APROVADA
-- 2 = REPROVADA
-- ============================================================
INSERT INTO materia (
    titulo,
    subtitulo,
    resumo,
    conteudo,
    data,
    status,
    nome_jornal,
    numero_edicao,
    id_setor
)
VALUES
(
    'Nova política de desenvolvimento regional',
    'Medidas devem ampliar investimentos',
    'Governo apresenta novas medidas para o desenvolvimento regional.',
    'O programa prevê investimentos em infraestrutura, educação e tecnologia para estimular o desenvolvimento regional.',
    '2026-01-05',
    0,
    'Jornal 01',
    1,
    1
),
(
    'Investimentos em educação avançam',
    'Novos projetos são anunciados',
    'Projetos educacionais devem beneficiar escolas públicas.',
    'As novas ações incluem reformas, aquisição de equipamentos e ampliação de programas educacionais.',
    '2026-01-06',
    1,
    'Jornal 01',
    1,
    2
),
(
    'Tecnologia transforma serviços públicos',
    'Digitalização ganha espaço',
    'Órgãos públicos ampliam o uso de ferramentas digitais.',
    'A transformação digital busca reduzir burocracias e melhorar o atendimento oferecido à população.',
    '2026-01-07',
    2,
    'Jornal 02',
    1,
    3
),
(
    'Novas ações para saúde pública',
    'Atendimento será ampliado',
    'Municípios anunciam medidas para melhorar os serviços de saúde.',
    'As iniciativas contemplam novas unidades, contratação de profissionais e modernização dos equipamentos.',
    '2026-01-08',
    0,
    'Jornal 02',
    1,
    4
),
(
    'Mercado regional apresenta crescimento',
    'Comércio registra novos resultados',
    'Atividade comercial apresenta evolução no início do ano.',
    'Empresas locais registraram aumento nas vendas e esperam manter o crescimento nos próximos meses.',
    '2026-01-09',
    1,
    'Jornal 03',
    1,
    5
),
(
    'Programa ambiental é ampliado',
    'Municípios aderem à iniciativa',
    'Novas cidades passaram a integrar o programa de preservação ambiental.',
    'A iniciativa prevê ações de educação ambiental, recuperação de áreas degradadas e fiscalização.',
    '2026-01-10',
    2,
    'Jornal 03',
    1,
    1
),
(
    'Obras de infraestrutura são iniciadas',
    'Projeto prevê melhorias urbanas',
    'Novas obras devem melhorar a mobilidade urbana.',
    'O projeto inclui recuperação de vias, construção de equipamentos públicos e melhorias na iluminação.',
    '2026-01-11',
    0,
    'Jornal 04',
    1,
    2
),
(
    'Universidades ampliam projetos de pesquisa',
    'Ciência recebe novos investimentos',
    'Instituições anunciam novos projetos científicos.',
    'Os investimentos serão destinados a laboratórios, bolsas acadêmicas e desenvolvimento de pesquisas.',
    '2026-01-12',
    1,
    'Jornal 04',
    1,
    3
),
(
    'Empresas apostam em inovação',
    'Novas soluções chegam ao mercado',
    'Empresas regionais aumentam investimentos em inovação.',
    'Startups e empresas tradicionais estão desenvolvendo novas soluções para atender às demandas dos consumidores.',
    '2026-01-13',
    2,
    'Jornal 05',
    1,
    4
),
(
    'Transporte público passa por mudanças',
    'Novas rotas entram em planejamento',
    'Sistema de transporte deverá receber melhorias.',
    'O planejamento prevê novas linhas e mudanças nas rotas para atender regiões com maior demanda.',
    '2026-01-14',
    0,
    'Jornal 05',
    1,
    5
),
(
    'Agricultura familiar recebe incentivo',
    'Produtores terão novas oportunidades',
    'Programa busca fortalecer pequenos produtores.',
    'A iniciativa oferece assistência técnica, capacitação e acesso facilitado a programas de financiamento.',
    '2026-01-15',
    1,
    'Jornal 01',
    2,
    1
),
(
    'Comércio local se prepara para novas demandas',
    'Empresários investem em planejamento',
    'Comerciantes buscam estratégias para aumentar a competitividade.',
    'Empresários estão investindo em capacitação, tecnologia e melhoria da experiência dos consumidores.',
    '2026-01-16',
    2,
    'Jornal 01',
    2,
    2
),
(
    'Campanha de vacinação é iniciada',
    'Unidades recebem novas doses',
    'Campanha pretende ampliar a cobertura vacinal.',
    'As unidades de saúde estão preparadas para atender a população durante as novas etapas da campanha.',
    '2026-01-17',
    0,
    'Jornal 02',
    2,
    3
),
(
    'Bibliotecas públicas recebem novos acervos',
    'Livros serão distribuídos',
    'Novos livros serão disponibilizados para leitores.',
    'A ação busca ampliar o acesso à leitura e fortalecer os espaços culturais dos municípios.',
    '2026-01-18',
    1,
    'Jornal 02',
    2,
    4
),
(
    'Projeto de mobilidade é apresentado',
    'Estudo analisa alternativas',
    'Especialistas apresentam propostas para melhorar a mobilidade.',
    'O estudo avalia diferentes alternativas de transporte e infraestrutura para reduzir congestionamentos.',
    '2026-01-19',
    2,
    'Jornal 03',
    2,
    5
),
(
    'Feira de tecnologia reúne empresas',
    'Evento apresenta novas soluções',
    'Empresas e pesquisadores participam de evento tecnológico.',
    'A programação inclui palestras, demonstrações de produtos e apresentação de projetos inovadores.',
    '2026-01-20',
    0,
    'Jornal 03',
    2,
    1
),
(
    'Parques urbanos recebem melhorias',
    'Áreas de lazer serão revitalizadas',
    'Espaços públicos passam por obras de revitalização.',
    'As intervenções incluem novos equipamentos, iluminação e recuperação das áreas de convivência.',
    '2026-01-21',
    1,
    'Jornal 04',
    2,
    2
),
(
    'Mercado de trabalho apresenta novas oportunidades',
    'Empresas anunciam vagas',
    'Novas oportunidades são disponibilizadas em diferentes setores.',
    'Empresas ampliaram seus processos seletivos para atender ao crescimento da demanda por profissionais.',
    '2026-01-22',
    2,
    'Jornal 04',
    2,
    3
),
(
    'Centro cultural recebe programação especial',
    'Eventos serão realizados durante o mês',
    'Centro cultural anuncia novas atividades.',
    'A programação reúne exposições, oficinas, apresentações musicais e atividades educativas.',
    '2026-01-23',
    0,
    'Jornal 05',
    2,
    4
),
(
    'Novas medidas para segurança urbana',
    'Projeto prevê ações integradas',
    'Órgãos públicos estudam novas medidas de segurança.',
    'O projeto prevê integração entre diferentes instituições e utilização de novas ferramentas tecnológicas.',
    '2026-01-24',
    1,
    'Jornal 05',
    2,
    5
),
(
    'Pesquisa aponta mudanças no consumo',
    'Hábitos dos consumidores são analisados',
    'Estudo identifica novas tendências de consumo.',
    'A pesquisa aponta mudanças no comportamento dos consumidores e crescimento das compras digitais.',
    '2026-01-25',
    2,
    'Jornal 01',
    1,
    3
),
(
    'Município amplia coleta seletiva',
    'Novos bairros serão atendidos',
    'Programa de coleta seletiva será expandido.',
    'A expansão pretende aumentar o volume de materiais reciclados e conscientizar os moradores.',
    '2026-01-26',
    0,
    'Jornal 02',
    1,
    5
),
(
    'Escolas recebem equipamentos tecnológicos',
    'Salas terão novos recursos',
    'Instituições de ensino recebem novos equipamentos.',
    'Computadores, projetores e outros recursos tecnológicos serão utilizados nas atividades pedagógicas.',
    '2026-01-27',
    1,
    'Jornal 03',
    1,
    2
),
(
    'Evento esportivo movimenta a cidade',
    'Competição reúne atletas',
    'Evento esportivo reúne participantes de diferentes municípios.',
    'A competição contará com diversas modalidades e atividades abertas ao público.',
    '2026-01-28',
    2,
    'Jornal 04',
    1,
    4
),
(
    'Plano de turismo é atualizado',
    'Setor busca novos visitantes',
    'Novas estratégias são apresentadas para o turismo regional.',
    'O plano pretende divulgar os principais destinos e melhorar a infraestrutura turística.',
    '2026-01-29',
    0,
    'Jornal 05',
    1,
    1
),
(
    'Novas oportunidades para pequenos negócios',
    'Programa oferece capacitação',
    'Empreendedores terão acesso a novos cursos.',
    'O programa oferece capacitação em gestão, marketing, finanças e planejamento empresarial.',
    '2026-01-30',
    1,
    'Jornal 01',
    2,
    4
),
(
    'Hospital recebe novos equipamentos',
    'Atendimento especializado será ampliado',
    'Unidade de saúde passa por modernização.',
    'Os novos equipamentos permitirão ampliar a capacidade de atendimento e realizar novos procedimentos.',
    '2026-02-01',
    2,
    'Jornal 02',
    2,
    1
),
(
    'Programa cultural chega a novas comunidades',
    'Atividades serão realizadas gratuitamente',
    'Projeto cultural amplia suas ações.',
    'Oficinas e apresentações serão realizadas em diferentes comunidades durante os próximos meses.',
    '2026-02-02',
    0,
    'Jornal 03',
    2,
    3
),
(
    'Novas medidas apoiam estudantes',
    'Programa oferece auxílio',
    'Estudantes poderão receber apoio para continuar os estudos.',
    'O programa prevê auxílio financeiro e acompanhamento educacional para estudantes em situação de vulnerabilidade.',
    '2026-02-03',
    1,
    'Jornal 04',
    2,
    5
),
(
    'Empresas investem em energia renovável',
    'Projetos sustentáveis ganham espaço',
    'Empresas anunciam novos projetos de energia limpa.',
    'Os projetos incluem instalação de sistemas solares e medidas para reduzir o consumo energético.',
    '2026-02-04',
    2,
    'Jornal 05',
    1,
    2
),
(
    'Obras de saneamento avançam',
    'Novas áreas serão atendidas',
    'Projeto de saneamento entra em nova etapa.',
    'As obras incluem expansão da rede de abastecimento e implantação de sistemas de tratamento.',
    '2026-02-05',
    0,
    'Jornal 01',
    1,
    5
),
(
    'Centro de inovação inicia atividades',
    'Espaço reúne empreendedores',
    'Novo centro pretende estimular projetos inovadores.',
    'O espaço oferecerá infraestrutura, capacitação e oportunidades de colaboração entre empresas.',
    '2026-02-06',
    1,
    'Jornal 02',
    1,
    3
),
(
    'Campanha de prevenção é lançada',
    'Ações serão realizadas durante o mês',
    'Campanha busca conscientizar a população.',
    'As atividades incluem palestras, distribuição de materiais informativos e atendimento especializado.',
    '2026-02-07',
    2,
    'Jornal 03',
    1,
    4
),
(
    'Novo sistema facilita atendimento',
    'Serviço passa a funcionar digitalmente',
    'Plataforma digital começa a ser utilizada.',
    'O novo sistema permite que usuários acompanhem solicitações e realizem procedimentos pela internet.',
    '2026-02-08',
    0,
    'Jornal 04',
    1,
    1
),
(
    'Festival regional anuncia programação',
    'Evento terá atrações diversas',
    'Festival prepara programação para o público.',
    'O evento contará com apresentações artísticas, atividades culturais e espaços destinados à gastronomia.',
    '2026-02-09',
    1,
    'Jornal 05',
    1,
    3
),
(
    'Novas linhas de crédito são disponibilizadas',
    'Empreendedores poderão solicitar financiamento',
    'Instituições anunciam novas condições de crédito.',
    'As linhas de financiamento possuem condições específicas para pequenos e médios empreendedores.',
    '2026-02-10',
    2,
    'Jornal 01',
    2,
    5
),
(
    'Projeto de arborização é ampliado',
    'Mais áreas receberão árvores',
    'Município amplia ações de arborização urbana.',
    'O projeto prevê o plantio de árvores em ruas, praças e áreas públicas.',
    '2026-02-11',
    0,
    'Jornal 02',
    2,
    2
),
(
    'Cursos profissionalizantes são anunciados',
    'Novas turmas serão abertas',
    'Programa oferece capacitação profissional.',
    'Os cursos abrangem diferentes áreas e pretendem facilitar a entrada dos participantes no mercado de trabalho.',
    '2026-02-12',
    1,
    'Jornal 03',
    2,
    4
),
(
    'Museu prepara nova exposição',
    'Acervo histórico será apresentado',
    'Museu anuncia exposição sobre a história regional.',
    'A exposição reúne documentos, fotografias e objetos que fazem parte da história da região.',
    '2026-02-13',
    2,
    'Jornal 04',
    2,
    1
),
(
    'Plano habitacional recebe novas propostas',
    'Projeto busca ampliar moradias',
    'Novas propostas são analisadas pelo poder público.',
    'O plano prevê construção de unidades habitacionais e melhorias em áreas já ocupadas.',
    '2026-02-14',
    0,
    'Jornal 05',
    2,
    3
),
(
    'Empresas adotam novas práticas ambientais',
    'Sustentabilidade ganha destaque',
    'Empresas ampliam suas ações ambientais.',
    'As iniciativas incluem redução de resíduos, economia de água e utilização de fontes renováveis.',
    '2026-02-15',
    1,
    'Jornal 01',
    1,
    4
),
(
    'Bibliotecas ampliam horários de atendimento',
    'Serviço será disponibilizado aos finais de semana',
    'Bibliotecas passam a atender em novos horários.',
    'A mudança pretende facilitar o acesso da população aos espaços de leitura e pesquisa.',
    '2026-02-16',
    2,
    'Jornal 02',
    1,
    5
),
(
    'Projeto esportivo atende novos jovens',
    'Atividades gratuitas são oferecidas',
    'Projeto amplia o atendimento a crianças e adolescentes.',
    'As atividades esportivas serão realizadas em diferentes espaços públicos.',
    '2026-02-17',
    0,
    'Jornal 03',
    1,
    1
),
(
    'Novas tecnologias chegam à agricultura',
    'Produtores adotam ferramentas digitais',
    'Tecnologia começa a ser utilizada no campo.',
    'Sensores, sistemas de monitoramento e ferramentas digitais ajudam produtores a melhorar a produtividade.',
    '2026-02-18',
    1,
    'Jornal 04',
    1,
    2
),
(
    'Plano de emergência é atualizado',
    'Órgãos revisam procedimentos',
    'Plano municipal passa por atualização.',
    'As mudanças buscam melhorar a capacidade de resposta das equipes em situações de emergência.',
    '2026-02-19',
    2,
    'Jornal 05',
    1,
    4
),
(
    'Novas ações para geração de empregos',
    'Programa aproxima empresas e trabalhadores',
    'Projeto busca facilitar a contratação de profissionais.',
    'A iniciativa pretende aproximar empresas que possuem vagas disponíveis de trabalhadores em busca de oportunidades.',
    '2026-02-20',
    0,
    'Jornal 01',
    2,
    3
),
(
    'Feira de negócios reúne empreendedores',
    'Evento promove parcerias',
    'Empresários participam de feira regional.',
    'O encontro promove oportunidades de negócios, palestras e apresentação de novos produtos.',
    '2026-02-21',
    1,
    'Jornal 02',
    2,
    5
),
(
    'Programa de leitura incentiva estudantes',
    'Escolas recebem novas atividades',
    'Projeto incentiva o hábito da leitura.',
    'As atividades incluem rodas de leitura, oficinas de escrita e encontros com autores.',
    '2026-02-22',
    2,
    'Jornal 03',
    2,
    2
),
(
    'Novas medidas de proteção ambiental',
    'Fiscalização será reforçada',
    'Órgãos ambientais anunciam novas ações.',
    'As medidas incluem fiscalização de áreas protegidas e ações educativas junto às comunidades.',
    '2026-02-23',
    0,
    'Jornal 04',
    2,
    4
),
(
    'Centro esportivo passa por reforma',
    'Espaço terá novos equipamentos',
    'Centro esportivo será modernizado.',
    'A reforma prevê melhorias nas quadras, vestiários e espaços destinados aos usuários.',
    '2026-02-24',
    1,
    'Jornal 05',
    2,
    1
),
(
    'Pesquisa analisa desenvolvimento econômico',
    'Estudo reúne dados regionais',
    'Pesquisadores analisam indicadores econômicos.',
    'O levantamento considera dados de emprego, renda, produção e atividade empresarial.',
    '2026-02-25',
    2,
    'Jornal 01',
    1,
    5
),
(
    'Novos serviços digitais são disponibilizados',
    'Usuários poderão realizar solicitações online',
    'Plataforma pública recebe novas funcionalidades.',
    'Os novos serviços permitem realizar solicitações sem necessidade de atendimento presencial.',
    '2026-02-26',
    0,
    'Jornal 02',
    1,
    2
),
(
    'Projeto de capacitação tecnológica',
    'Cursos serão oferecidos gratuitamente',
    'Programa pretende ampliar conhecimentos digitais.',
    'Os participantes poderão aprender conceitos de informática, programação e ferramentas digitais.',
    '2026-02-27',
    1,
    'Jornal 03',
    1,
    3
),
(
    'Novos investimentos em infraestrutura',
    'Recursos serão destinados a obras',
    'Governo anuncia novos investimentos.',
    'Os recursos serão destinados à melhoria de estradas, prédios públicos e sistemas urbanos.',
    '2026-02-28',
    2,
    'Jornal 04',
    1,
    5
),
(
    'Campanha incentiva consumo consciente',
    'Ações educativas serão realizadas',
    'Projeto busca incentivar hábitos sustentáveis.',
    'A campanha apresenta orientações para redução do desperdício e consumo responsável.',
    '2026-03-01',
    0,
    'Jornal 05',
    1,
    2
),
(
    'Novas oportunidades no setor de serviços',
    'Empresas ampliam contratações',
    'Setor de serviços apresenta novas oportunidades.',
    'Empresas estão ampliando suas equipes diante do aumento da demanda por serviços especializados.',
    '2026-03-02',
    1,
    'Jornal 01',
    2,
    4
),
(
    'Programa de inovação recebe inscrições',
    'Empreendedores podem participar',
    'Programa abre inscrições para novos projetos.',
    'Os participantes poderão apresentar projetos inovadores e receber orientação técnica.',
    '2026-03-03',
    2,
    'Jornal 02',
    2,
    1
),
(
    'Projeto cultural recebe novos recursos',
    'Atividades serão ampliadas',
    'Projeto cultural recebe investimento adicional.',
    'Os novos recursos permitirão ampliar oficinas, apresentações e atividades educativas.',
    '2026-03-04',
    0,
    'Jornal 03',
    2,
    3
),
(
    'Sistema de transporte recebe melhorias',
    'Novos equipamentos serão instalados',
    'Sistema passa por modernização.',
    'Novos equipamentos deverão melhorar o controle e o funcionamento do transporte público.',
    '2026-03-05',
    1,
    'Jornal 04',
    2,
    5
),
(
    'Ações de saúde preventiva são ampliadas',
    'Equipes atenderão novas regiões',
    'Programa de prevenção amplia seu alcance.',
    'As equipes realizarão atendimentos e atividades educativas em diferentes regiões.',
    '2026-03-06',
    2,
    'Jornal 05',
    2,
    2
),
(
    'Novos projetos de pesquisa científica',
    'Universidades apresentam iniciativas',
    'Instituições apresentam projetos de pesquisa.',
    'Os projetos abrangem tecnologia, meio ambiente, saúde e desenvolvimento social.',
    '2026-03-07',
    0,
    'Jornal 01',
    1,
    4
),
(
    'Comércio eletrônico ganha novos usuários',
    'Empresas ampliam presença digital',
    'Comércio digital continua crescendo.',
    'Empresas locais estão investindo em plataformas digitais para ampliar o alcance dos seus produtos.',
    '2026-03-08',
    1,
    'Jornal 02',
    1,
    5
),
(
    'Novas ações para preservação histórica',
    'Patrimônio recebe atenção especial',
    'Projeto busca preservar patrimônio histórico.',
    'As ações incluem restauração, catalogação e divulgação de bens históricos.',
    '2026-03-09',
    2,
    'Jornal 03',
    1,
    1
),
(
    'Programa de esporte escolar é ampliado',
    'Alunos terão novas atividades',
    'Programa esportivo passa a atender novas escolas.',
    'A iniciativa oferece atividades esportivas e acompanhamento para estudantes.',
    '2026-03-10',
    0,
    'Jornal 04',
    1,
    3
),
(
    'Novas estratégias para desenvolvimento local',
    'Municípios planejam ações conjuntas',
    'Gestores apresentam estratégias de desenvolvimento.',
    'As propostas buscam estimular investimentos, geração de empregos e melhoria dos serviços públicos.',
    '2026-03-11',
    1,
    'Jornal 05',
    1,
    4
),
(
    'Projeto de inclusão digital é ampliado',
    'Comunidades recebem novos equipamentos',
    'Programa amplia acesso à tecnologia.',
    'Novos espaços receberão computadores e conexão para oferecer capacitação digital.',
    '2026-03-12',
    2,
    'Jornal 01',
    2,
    2
),
(
    'Novas ações de apoio ao empreendedor',
    'Programa oferece orientação especializada',
    'Empreendedores recebem novos serviços de apoio.',
    'A iniciativa oferece consultorias e capacitações para melhorar a gestão dos negócios.',
    '2026-03-13',
    0,
    'Jornal 02',
    2,
    4
),
(
    'Projeto de recuperação de áreas degradadas',
    'Equipes iniciam trabalhos',
    'Áreas ambientais serão recuperadas.',
    'O projeto prevê recuperação da vegetação e acompanhamento das áreas durante os próximos anos.',
    '2026-03-14',
    1,
    'Jornal 03',
    2,
    5
),
(
    'Novas atividades em centros comunitários',
    'Espaços recebem programação',
    'Centros comunitários ampliam suas atividades.',
    'Os espaços oferecerão cursos, oficinas, reuniões e atividades voltadas à comunidade.',
    '2026-03-15',
    2,
    'Jornal 04',
    2,
    1
),
(
    'Plano de modernização administrativa',
    'Órgãos adotam novas ferramentas',
    'Projeto busca modernizar processos administrativos.',
    'A modernização prevê digitalização de documentos e utilização de sistemas integrados.',
    '2026-03-16',
    0,
    'Jornal 05',
    2,
    3
),
(
    'Novas ações de incentivo à leitura',
    'Projeto chega a novas escolas',
    'Programa de leitura amplia sua atuação.',
    'Novas escolas passarão a participar de atividades de leitura e produção textual.',
    '2026-03-17',
    1,
    'Jornal 01',
    1,
    5
),
(
    'Programa ambiental recebe novos participantes',
    'Comunidades aderem ao projeto',
    'Novas comunidades passam a participar do programa.',
    'As ações incluem coleta seletiva, educação ambiental e recuperação de espaços públicos.',
    '2026-03-18',
    2,
    'Jornal 02',
    1,
    2
),
(
    'Novas soluções para mobilidade urbana',
    'Estudos avaliam alternativas',
    'Especialistas analisam novas soluções de transporte.',
    'Os estudos avaliam alternativas para melhorar o deslocamento da população e reduzir congestionamentos.',
    '2026-03-19',
    0,
    'Jornal 03',
    1,
    4
),
(
    'Projeto de qualificação profissional',
    'Novos cursos serão oferecidos',
    'Programa amplia oportunidades de capacitação.',
    'Os cursos serão voltados para áreas com maior demanda no mercado de trabalho regional.',
    '2026-03-20',
    1,
    'Jornal 04',
    1,
    1
),
(
    'Novas ações de desenvolvimento sustentável',
    'Projetos recebem apoio',
    'Programa reúne iniciativas sustentáveis.',
    'Os projetos buscam conciliar desenvolvimento econômico, preservação ambiental e melhoria da qualidade de vida.',
    '2026-03-21',
    2,
    'Jornal 05',
    1,
    3
);